#pragma once
#include <Arduino.h>

static const char INDEX_HTML[] PROGMEM = R"HTML(
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Kiln Controller</title>
<style>
:root{color-scheme:dark;--bg:#101217;--card:#191d24;--line:#303641;--text:#edf2f7;--muted:#9aa4b2;--accent:#4c8dff;--danger:#d95555;--good:#52b788;--warn:#d6a84b}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,sans-serif}header{padding:16px 20px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}h1,h2,h3{margin:.2em 0}.tabs{display:flex;gap:8px;padding:12px 18px;position:sticky;top:0;background:var(--bg);z-index:4}.tabs button,.btn{border:1px solid var(--line);background:#232833;color:var(--text);border-radius:8px;padding:9px 13px;cursor:pointer}.tabs button.active,.btn.primary{background:var(--accent);border-color:var(--accent)}.btn.danger{background:#442323;border-color:#7c3434}.btn.good{background:#214331;border-color:#386d50}.tab{display:none;padding:0 18px 28px}.tab.active{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:15px}.metric{font-size:30px;font-weight:700}.muted{color:var(--muted)}.warn{color:#ffd27a}.bad{color:#ff8585}.goodtxt{color:#75d6a5}.row{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.controls{margin-top:12px}input,select{background:#0f1217;color:var(--text);border:1px solid var(--line);border-radius:7px;padding:8px;max-width:100%}.formgrid{display:grid;grid-template-columns:minmax(160px,1fr) minmax(120px,1fr);gap:9px 14px;align-items:center}.section{margin-top:12px}canvas{width:100%;height:auto;background:#11151b;border-radius:8px}.program-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:9px}.program-card{padding:13px;border:1px solid var(--line);border-radius:9px;background:#202630;cursor:pointer}.program-card:hover{border-color:var(--accent)}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid var(--line);padding:7px;text-align:left}td input{width:100%}.msg{min-height:22px;color:#89b4ff;margin-top:8px}dialog{background:var(--card);color:var(--text);border:1px solid var(--line);border-radius:12px;min-width:min(420px,92vw)}dialog::backdrop{background:#0009}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#2a303b}.hidden{display:none!important}.toast{position:fixed;right:16px;bottom:16px;max-width:360px;background:#243044;border:1px solid #4c8dff;padding:14px 16px;border-radius:10px;z-index:20;box-shadow:0 8px 30px #0008}.toast.badtoast{border-color:#d95555;background:#402727}progress{width:100%}@media(max-width:600px){.formgrid{grid-template-columns:1fr}.metric{font-size:26px}}
</style></head><body>
<header><div><h2>Kiln Controller</h2><div class="muted" id="topState">Connecting...</div></div><div id="topWifi" class="muted"></div></header>
<nav class="tabs"><button class="active" data-tab="main">Main</button><button data-tab="programs">Saved programs</button><button data-tab="settings">Settings</button></nav>
<div id="toast" class="toast hidden"></div>
<main>
<section id="main" class="tab active">
  <div class="grid">
    <div class="card"><div class="muted">Temperature</div><div class="metric" id="temp">-- °C</div><div>Target <b id="target">--</b></div></div>
    <div class="card"><div class="muted">Power</div><div class="metric" id="power">-- %</div><div>Step limit <b id="powerLimit">--</b></div></div>
    <div class="card"><div class="muted">Timing</div><div>Elapsed <b id="elapsed">--</b></div><div>Remaining <b id="remaining">--</b></div><div>ETA confidence <b id="eta">--</b></div></div>
    <div class="card"><div class="muted">Ramp</div><div>Requested <b id="requestedRate">--</b></div><div>Actual <b id="actualRate">--</b></div><div id="lagState"></div></div>
  </div>

  <div class="card section">
    <div class="row"><b id="activeProgram">Idle</b><span class="pill" id="stepInfo"></span></div>
    <div class="row controls">
      <button class="btn" id="pauseBtn">Pause / hold</button>
      <button class="btn" id="resumeBtn">Resume</button>
      <button class="btn danger" id="stopBtn">Stop</button>
      <button class="btn" id="notifyBtn">Enable notifications</button>
    </div>
  </div>

  <div class="card section" id="recoveryCard" style="display:none">
    <h3>Interrupted firing found</h3><p id="recoveryText"></p>
    <div class="row"><button class="btn good" id="recoveryResume">Resume</button><button class="btn danger" id="recoveryDiscard">Discard</button></div>
  </div>

  <div class="card section">
    <h3>Start a saved program</h3><div class="program-grid" id="mainPrograms"></div>
  </div>

  <div class="grid section">
    <div class="card"><h3>Manual temperature</h3><div class="row"><input id="manualTemp" type="number" value="100" min="0" step="1"><span>°C</span><button class="btn primary" id="manualTempStart">Start</button></div></div>
    <div class="card"><h3>Manual power</h3><div class="row"><input id="manualPower" type="number" value="25" min="0" max="100" step="1"><span>%</span><button class="btn primary" id="manualPowerStart">Start</button></div><p class="muted">Temperature safety and timeout remain active.</p></div>
  </div>

  <div class="card section"><div class="row"><h3 style="flex:1">Current firing</h3><button class="btn range" data-sec="1800">30m</button><button class="btn range" data-sec="3600">1h</button><button class="btn range" data-sec="10800">3h</button><button class="btn range primary" data-sec="0">All</button><label><input id="autoY" type="checkbox" checked> Auto Y</label></div><canvas id="liveGraph" width="900" height="330"></canvas><p class="muted">Blue = actual temperature, dashed = programmed target.</p></div>

  <div class="card section"><h3>Last 5 program runs</h3><table><thead><tr><th>Program</th><th>Result</th><th>Actual elapsed time</th></tr></thead><tbody id="runsBody"></tbody></table></div>
</section>

<section id="programs" class="tab">
  <div class="grid"><div class="card"><h3>Programs</h3><div id="programList" class="program-grid"></div><div class="row controls"><button class="btn" id="newProgram">New</button><button class="btn" id="duplicateProgram">Duplicate</button><button class="btn danger" id="deleteProgram">Delete</button></div></div><div class="card"><h3>Profile preview</h3><canvas id="programGraph" width="700" height="280"></canvas></div></div>
  <div class="card section"><div class="formgrid"><label>Name</label><input id="programName"></div><table><thead><tr><th>#</th><th>Target °C</th><th>Rate °C/h</th><th>Hold min</th><th>Max power %</th><th></th></tr></thead><tbody id="stepsBody"></tbody></table><div class="row controls"><button class="btn" id="addStep">Add step</button><button class="btn primary" id="savePrograms">Save programs</button></div><div class="msg" id="programMsg"></div></div>
</section>

<section id="settings" class="tab">
  <div class="card"><h3>PID / temperature control</h3><div class="formgrid"><label>P</label><input id="kp" type="number" step="0.01"><label>I</label><input id="ki" type="number" step="0.001"><label>D</label><input id="kd" type="number" step="0.01"><label>Global max output %</label><input id="maxOutput" type="number" min="0" max="100"></div></div>
  <div class="card section"><h3>Thermocouple</h3><div class="formgrid"><label>Temperature offset °C</label><input id="tcOffset" type="number" step="0.1"><label>Raw temperature</label><span id="rawTemp">--</span></div></div>
  <div class="card section"><h3>Safety</h3><div class="formgrid"><label>Maximum temperature °C</label><input id="maxTemp" type="number"><label>Maximum overshoot °C</label><input id="maxOvershoot" type="number"><label>Manual power max %</label><input id="manualPowerMax" type="number"><label>Manual power temp cutoff °C</label><input id="manualPowerTempLimit" type="number"><label>Manual power timeout min</label><input id="manualPowerTimeoutMin" type="number"></div></div>
  <div class="card section"><h3>Connectivity</h3><div class="formgrid"><label>Status</label><span id="wifiStatus">--</span><label>Network</label><span id="wifiNow">--</span><label>Station IP</label><span id="ipNow">--</span><label>Signal</label><span id="rssiNow">--</span><label>Setup hotspot</label><span id="apNow">--</span><label>Hostname</label><input id="hostname"><label>Wi-Fi SSID</label><input id="ssid"><label>Wi-Fi password</label><input id="wifiPass" type="password" placeholder="leave blank to keep current"></div><div class="row controls"><button class="btn" id="startAp">Start setup hotspot</button><button class="btn" id="stopAp">Stop hotspot</button><button class="btn" id="retryWifi">Retry Wi-Fi</button><button class="btn primary" id="saveWifi">Save Wi-Fi & restart</button></div><p class="muted">The hotspot is never started automatically. Start it only here or from the local menu.</p></div>
  <div class="card section"><h3>System / firmware</h3><div class="formgrid"><label>Firmware</label><span id="firmwareVersion">--</span><label>Real heater output</label><span id="heaterEnabled">--</span><label>Firmware .bin</label><input id="firmwareFile" type="file" accept=".bin,application/octet-stream"></div><div class="row controls"><button class="btn primary" id="uploadFirmware">Upload & install</button><button class="btn" id="restart">Restart</button><button class="btn danger" id="factoryReset">Factory reset</button></div><progress id="otaProgress" value="0" max="100" style="display:none"></progress></div>
  <div class="row section"><button class="btn primary" id="saveSettings">Save settings</button></div><div class="msg" id="settingsMsg"></div>
</section>
</main>

<dialog id="programDialog"><h3 id="dialogProgramName">Program</h3><p>Choose how to start this program.</p><div class="row"><button class="btn primary" id="dialogStartNow">Start now</button></div><hr style="border-color:#303641"><label>Delayed start</label><div class="row"><input id="delayMinutes" type="number" min="15" max="2880" step="15" value="60"><span>minutes</span><button class="btn" id="dialogStartDelayed">Start delayed</button></div><p class="muted">15-minute increments. Heater output remains 0% until the countdown finishes.</p><button class="btn" id="dialogClose">Close</button></dialog>

<script>
const $=id=>document.getElementById(id);let programs=[],selectedProgram=0,live=[],rangeSec=0,lastStatus=null,lastEventCounter=null;
function msg(id,t){$(id).textContent=t;setTimeout(()=>{if($(id).textContent===t)$(id).textContent=''},3500)}
function fmt(sec){if(sec===null||sec===undefined||sec<0)return'--';sec=Math.round(sec);let h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h>0?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function programSeconds(p,startTemp){if(!p)return 0;let temp=Number.isFinite(startTemp)?startTemp:20,total=0;for(const s of p.steps||[]){let rate=Math.max(1,Math.abs(+s.rate||0));total+=Math.abs((+s.target||0)-temp)/rate*3600;total+=(+s.hold||0)*60;temp=+s.target||0}return Math.round(total)}
function fmtProgram(sec){sec=Math.max(0,Math.round(sec||0));let h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);return h?`${h}h ${m}m`:`${m}m`}
async function api(url,opt){let r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.headers.get('content-type')?.includes('json')?r.json():r.text()}
for(const b of document.querySelectorAll('.tabs button'))b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));if(b.dataset.tab==='programs')drawProgramGraph();if(b.dataset.tab==='settings')loadSettings().catch(()=>{})};
for(const b of document.querySelectorAll('.range'))b.onclick=()=>{rangeSec=+b.dataset.sec;document.querySelectorAll('.range').forEach(x=>x.classList.toggle('primary',x===b));drawLiveGraph()};$('autoY').onchange=drawLiveGraph;

function openProgram(i){selectedProgram=i;let p=programs[i],dur=programSeconds(p,20);$('dialogProgramName').textContent=(p?.name||'Program')+' — '+fmtProgram(dur);$('programDialog').showModal()}
$('dialogClose').onclick=()=>$('programDialog').close();
$('dialogStartNow').onclick=async()=>{try{await api('/api/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({index:selectedProgram})});$('programDialog').close()}catch(e){alert(e.message)}};
$('dialogStartDelayed').onclick=async()=>{let delay=Math.max(15,Math.round(+$('delayMinutes').value/15)*15);try{await api('/api/delayed-start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({index:selectedProgram,delayMin:delay})});$('programDialog').close()}catch(e){alert(e.message)}};

async function loadPrograms(){let d=await api('/api/programs');programs=d.programs||[];selectedProgram=Math.min(selectedProgram,Math.max(0,programs.length-1));renderMainPrograms();renderProgramEditor()}
function renderMainPrograms(){let box=$('mainPrograms');box.innerHTML='';programs.forEach((p,i)=>{let b=document.createElement('div');b.className='program-card';let dur=programSeconds(p,20);b.innerHTML=`<div class="row" style="justify-content:space-between"><b>${p.name}</b><span>${fmtProgram(dur)}</span></div><div class="muted">${p.steps.length} step${p.steps.length===1?'':'s'} · nominal from 20 °C</div>`;b.onclick=()=>openProgram(i);box.appendChild(b)})}
function renderProgramEditor(){let list=$('programList');list.innerHTML='';programs.forEach((p,i)=>{let b=document.createElement('div');b.className='program-card';b.style.borderColor=i===selectedProgram?'#4c8dff':'';b.innerHTML=`<b>${p.name}</b><div class="muted">${fmtProgram(programSeconds(p,20))}</div>`;b.onclick=()=>{selectedProgram=i;renderProgramEditor()};list.appendChild(b)});let p=programs[selectedProgram];if(!p){$('programName').value='';$('stepsBody').innerHTML='';return}$('programName').value=p.name;let tb=$('stepsBody');tb.innerHTML='';p.steps.forEach((s,i)=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td><input type="number" value="${s.target}"></td><td><input type="number" min="1" value="${s.rate}"></td><td><input type="number" min="0" value="${s.hold}"></td><td><input type="number" min="0" max="100" value="${s.maxPower??100}"></td><td><button class="btn danger">×</button></td>`;let ins=tr.querySelectorAll('input');ins[0].oninput=()=>{s.target=+ins[0].value;drawProgramGraph()};ins[1].oninput=()=>{s.rate=+ins[1].value;drawProgramGraph()};ins[2].oninput=()=>{s.hold=+ins[2].value;drawProgramGraph()};ins[3].oninput=()=>s.maxPower=+ins[3].value;tr.querySelector('button').onclick=()=>{p.steps.splice(i,1);renderProgramEditor()};tb.appendChild(tr)});drawProgramGraph()}
$('programName').oninput=()=>{if(programs[selectedProgram]){programs[selectedProgram].name=$('programName').value;renderMainPrograms()}};$('newProgram').onclick=()=>{programs.push({name:'New program',steps:[{target:100,rate:100,hold:0,maxPower:100}]});selectedProgram=programs.length-1;renderProgramEditor();renderMainPrograms()};$('duplicateProgram').onclick=()=>{if(!programs[selectedProgram])return;let p=JSON.parse(JSON.stringify(programs[selectedProgram]));p.name+=' copy';programs.push(p);selectedProgram=programs.length-1;renderProgramEditor();renderMainPrograms()};$('deleteProgram').onclick=()=>{if(programs.length<=1)return msg('programMsg','Keep at least one program');programs.splice(selectedProgram,1);selectedProgram=Math.max(0,selectedProgram-1);renderProgramEditor();renderMainPrograms()};$('addStep').onclick=()=>{let p=programs[selectedProgram];if(!p)return;p.steps.push({target:p.steps.length?p.steps[p.steps.length-1].target:100,rate:100,hold:0,maxPower:100});renderProgramEditor()};$('savePrograms').onclick=async()=>{try{await api('/api/programs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({programs})});msg('programMsg','Programs saved');renderMainPrograms()}catch(e){msg('programMsg',e.message)}};

function axes(ctx,w,h,minY,maxY){ctx.clearRect(0,0,w,h);ctx.strokeStyle='#303641';ctx.lineWidth=1;for(let i=0;i<5;i++){let y=20+(h-40)*i/4;ctx.beginPath();ctx.moveTo(45,y);ctx.lineTo(w-10,y);ctx.stroke();ctx.fillStyle='#9aa4b2';ctx.font='11px system-ui';ctx.fillText(Math.round(maxY-(maxY-minY)*i/4),4,y+4)}ctx.strokeStyle='#555';ctx.beginPath();ctx.moveTo(45,20);ctx.lineTo(45,h-20);ctx.lineTo(w-10,h-20);ctx.stroke()}
function drawProgramGraph(){let c=$('programGraph'),ctx=c.getContext('2d'),p=programs[selectedProgram];if(!p)return;let pts=[[0,20]],t=0,temp=20,max=100;for(const s of p.steps){let rate=Math.max(1,Math.abs(s.rate));t+=Math.abs(s.target-temp)/rate;temp=s.target;pts.push([t,temp]);if(s.hold>0){t+=s.hold/60;pts.push([t,temp])}max=Math.max(max,temp)}axes(ctx,c.width,c.height,0,max*1.08);let xmax=Math.max(.1,t);ctx.strokeStyle='#60a5fa';ctx.lineWidth=2;ctx.beginPath();pts.forEach((q,i)=>{let x=45+(c.width-55)*q[0]/xmax,y=20+(c.height-40)*(1-q[1]/(max*1.08));i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#9aa4b2';ctx.fillText(`${t.toFixed(1)} h nominal profile time`,50,c.height-5)}
function drawLiveGraph(){let c=$('liveGraph'),ctx=c.getContext('2d');if(!live.length){axes(ctx,c.width,c.height,0,100);return}let latest=live[live.length-1].t,data=rangeSec?live.filter(p=>p.t>=latest-rangeSec):live,minY=0,maxY=1300;if($('autoY').checked){let vals=[];for(const p of data){if(Number.isFinite(p.temp))vals.push(p.temp);if(Number.isFinite(p.target))vals.push(p.target)}if(vals.length){minY=Math.max(0,Math.min(...vals)-20);maxY=Math.max(minY+50,Math.max(...vals)+20)}}axes(ctx,c.width,c.height,minY,maxY);let t0=data[0].t,t1=Math.max(t0+1,data[data.length-1].t);function line(key,color,dash){ctx.strokeStyle=color;ctx.setLineDash(dash||[]);ctx.lineWidth=2;ctx.beginPath();let started=false;for(const p of data){if(!Number.isFinite(p[key])){started=false;continue}let x=45+(c.width-55)*(p.t-t0)/(t1-t0),y=20+(c.height-40)*(1-(p[key]-minY)/(maxY-minY));if(started)ctx.lineTo(x,y);else{ctx.moveTo(x,y);started=true}}ctx.stroke();ctx.setLineDash([])}line('temp','#60a5fa');line('target','#fbbf24',[8,5])}
async function loadHistory(){try{let d=await api('/api/history');live=d.samples||[];drawLiveGraph()}catch(e){}}
async function loadRuns(){try{let d=await api('/api/runs'),tb=$('runsBody');tb.innerHTML='';(d.runs||[]).forEach(r=>{let tr=document.createElement('tr');tr.innerHTML=`<td>${r.program}</td><td>${r.result}</td><td>${fmt(r.elapsed)}</td>`;tb.appendChild(tr)});if(!tb.children.length)tb.innerHTML='<tr><td colspan="3" class="muted">No completed or interrupted program runs yet.</td></tr>'}catch(e){}}

let audioCtx=null;function showToast(text,isBad){let t=$('toast');t.textContent=text;t.classList.remove('hidden');t.classList.toggle('badtoast',!!isBad);setTimeout(()=>t.classList.add('hidden'),7000)}function beep(){try{if(!audioCtx)return;let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=880;g.gain.value=.08;o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.25)}catch(e){}}function maybeNotify(s){if(lastEventCounter===null){lastEventCounter=s.eventCounter;return}if(s.eventCounter!==lastEventCounter){lastEventCounter=s.eventCounter;if(!s.eventMessage)return;showToast(s.eventMessage,s.eventType==='fault');document.title='Kiln: '+s.eventMessage;setTimeout(()=>document.title='Kiln Controller',8000);beep();if(('Notification'in window)&&Notification.permission==='granted')new Notification('Kiln Controller',{body:s.eventMessage})}}
$('notifyBtn').onclick=async()=>{try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();await audioCtx.resume()}catch(e){}if('Notification'in window){try{let p=await Notification.requestPermission();$('notifyBtn').textContent=p==='granted'?'Notifications enabled':'In-page alerts enabled'}catch(e){$('notifyBtn').textContent='In-page alerts enabled'}}else $('notifyBtn').textContent='In-page alerts enabled';showToast('Kiln alerts enabled while this page is open',false)};
async function pollStatus(){try{let s=await api('/api/status');lastStatus=s;$('topState').textContent=s.state+((s.fault)?' — '+s.fault:'');$('topWifi').textContent=s.wifiConnected?s.ip:'Wi-Fi '+s.wifiStatus;$('temp').textContent=`${Number(s.temp).toFixed(1)} °C`;$('target').textContent=s.hasTarget?`${Number(s.target).toFixed(1)} °C`:'--';$('power').textContent=`${Number(s.power).toFixed(0)} %`;$('powerLimit').textContent=`${Number(s.powerLimit).toFixed(0)} %`;$('elapsed').textContent=fmt(s.elapsed);$('remaining').textContent=fmt(s.remaining);$('eta').textContent=s.etaConfidence;$('requestedRate').textContent=`${Number(s.requestedRate).toFixed(0)} °C/h`;$('actualRate').textContent=s.rateValid?`${Number(s.actualRate).toFixed(0)} °C/h`:'--';$('lagState').innerHTML=s.lagging?'<span class="warn">Kiln is lagging behind the requested ramp; ETA adjusted.</span>':'<span class="goodtxt">No sustained ramp lag detected.</span>';$('activeProgram').textContent=s.programName||s.state;$('stepInfo').textContent=s.stepInfo||'';$('pauseBtn').style.display=s.state==='RUNNING'||s.state==='HOLD'?'':'none';$('resumeBtn').style.display=s.state==='PAUSED'?'':'none';$('recoveryCard').style.display=s.recoveryAvailable?'block':'none';if(s.recoveryAvailable)$('recoveryText').textContent=`${s.recoveryProgram}, previously elapsed ${fmt(s.recoveryElapsed)}.`;maybeNotify(s)}catch(e){$('topState').textContent='Connection lost'}}
$('pauseBtn').onclick=()=>api('/api/pause',{method:'POST'}).catch(e=>alert(e.message));$('resumeBtn').onclick=()=>api('/api/resume',{method:'POST'}).catch(e=>alert(e.message));$('stopBtn').onclick=()=>api('/api/stop',{method:'POST'}).catch(e=>alert(e.message));$('manualTempStart').onclick=()=>api('/api/manual-temp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:+$('manualTemp').value})}).catch(e=>alert(e.message));$('manualPowerStart').onclick=()=>api('/api/manual-power',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({power:+$('manualPower').value})}).catch(e=>alert(e.message));$('recoveryResume').onclick=()=>api('/api/recovery/resume',{method:'POST'}).catch(e=>alert(e.message));$('recoveryDiscard').onclick=()=>api('/api/recovery/discard',{method:'POST'}).catch(e=>alert(e.message));

async function loadSettings(){let s=await api('/api/settings');for(const k of ['kp','ki','kd','tcOffset','maxTemp','maxOutput','maxOvershoot','manualPowerMax','manualPowerTempLimit','manualPowerTimeoutMin','hostname'])if($(k))$(k).value=s[k];$('rawTemp').textContent=`${Number(s.rawTemp).toFixed(1)} °C`;$('wifiStatus').textContent=s.wifiStatus;$('wifiNow').textContent=s.ssid||'--';$('ipNow').textContent=s.ip;$('rssiNow').textContent=s.rssi?`${s.rssi} dBm`:'--';$('apNow').textContent=s.apActive?`ON — ${s.apIp}`:'OFF';$('ssid').value=s.ssid||'';$('firmwareVersion').textContent=s.firmware;$('heaterEnabled').textContent=s.heaterEnabled?'ENABLED':'Disabled for safe testing'}
$('saveSettings').onclick=async()=>{let d={};for(const k of ['kp','ki','kd','tcOffset','maxTemp','maxOutput','maxOvershoot','manualPowerMax','manualPowerTempLimit','manualPowerTimeoutMin'])d[k]=+$(k).value;d.hostname=$('hostname').value;try{await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});msg('settingsMsg','Settings saved')}catch(e){msg('settingsMsg',e.message)}};
$('saveWifi').onclick=async()=>{try{await api('/api/wifi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:$('ssid').value,password:$('wifiPass').value})});msg('settingsMsg','Saved; controller restarting...')}catch(e){msg('settingsMsg',e.message)}};$('startAp').onclick=()=>api('/api/ap/start',{method:'POST'}).then(loadSettings).catch(e=>alert(e.message));$('stopAp').onclick=()=>api('/api/ap/stop',{method:'POST'}).then(loadSettings).catch(e=>alert(e.message));$('retryWifi').onclick=()=>api('/api/wifi/retry',{method:'POST'}).then(()=>msg('settingsMsg','Wi-Fi retry requested')).catch(e=>alert(e.message));
$('restart').onclick=()=>{if(confirm('Restart controller?'))api('/api/restart',{method:'POST'}).catch(e=>alert(e.message))};$('factoryReset').onclick=()=>{if(confirm('Factory reset? Saved programs, settings and run history will be erased.'))api('/api/factory-reset',{method:'POST'}).catch(e=>alert(e.message))};
$('uploadFirmware').onclick=()=>{let f=$('firmwareFile').files[0];if(!f)return alert('Choose firmware.bin first');let x=new XMLHttpRequest(),fd=new FormData();fd.append('firmware',f);$('otaProgress').style.display='block';x.upload.onprogress=e=>{if(e.lengthComputable)$('otaProgress').value=100*e.loaded/e.total};x.onload=()=>alert(x.responseText);x.open('POST','/api/ota');x.send(fd)};

setInterval(pollStatus,1000);setInterval(loadHistory,5000);setInterval(loadRuns,10000);pollStatus();loadPrograms();loadHistory();loadRuns();loadSettings().catch(()=>{});
</script></body></html>
)HTML";
